config/routes.rb
Rails.application.routes.draw do
get 'users/reports', as: 'reports'
get 'users/all_report', as: 'all_report'
  devise_for :users

  resources :users do
    resources :reminders
  end

  root 'users#index'

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'csv'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reminders

 def self.to_csv
    CSV.generate do |csv|
      csv << User.new.attributes.keys
      User.all.each do |user|
        csv << user.attributes.values
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def index
    @reminders = Reminder.all
    set_user
  end

  def show
  end

  def edit
  end

  def new
    set_user
    @reminder = Reminder.new
  end

    def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def reminder_params
    params.require(:reminder).permit(:message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @reminders = Reminder.all
  end

  def edit
  end

  def new
    @user = User.new
  end

  def reports
  end

  def all_report
    respond_to do |format|
      format.csv do
      render text: User.to_csv
      end
    end
  end

# respond_to do |format|
#   format.csv do
#     send_data User.to_csv, filename: 'users_report.csv', disposition: 'download'
#   end
#   format.html do
#     render layout: false
#   end
  # format.pdf do
  #   send_data PDFKit.new(all_report_url(format: 'html')), filename: 'all_report.pdf'
  # end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class='container'>
  <div>
   <%= link_to 'SIGN-OUT', destroy_user_session_path(@user), method: :delete %> |
   <%= link_to "REPORTS", reports_path %>
  </div>

 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>

</div>

</body>
</html>

app/views/reminders/_form.html.erb
<%= simple_form_for([@user, @reminder]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/reminders/index.html.erb
<h1>Listing Users</h1>
<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.message %></td>
        <td><%= link_to 'Show', user_reminder_path(@user, reminder) %> | </td>
        <td><%= link_to 'Edit', edit_user_reminder_path(@user, reminder) %> | </td>
        <td><%= link_to 'Destroy', user_reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', user_reminders_path(@user) %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>





<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= link_to 'Show', user %> | </td>
        <td><%= link_to 'Edit', edit_user_path(user) %> | </td>
        <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/reports.html.erb
<p><%= link_to "All Report (as CSV)", all_report_path('csv') %></p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<table>
  <thead>
    <tr>
      <th>Message</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder %></td>
        <td><%= reminder.message %></td>
        <td><%= link_to 'Show', user_reminder_path(@user, reminder) %> | </td>
        <td><%= link_to 'Edit', edit_user_reminder_path(@user, reminder) %> | </td>
        <td><%= link_to 'Destroy', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>